# Test Automations File

- action:
  - data: {}
    service: light.turn_on
    target:
      entity_id: light.living_room
  alias: Turn on lights at sunset
  condition: []
  description: Turns on the living room lights when the sun sets
  id: '1741126745885'
  mode: single
  trigger:
  - event: sunset
    offset: +00:00:00
    platform: sun

# Another automation
- action:
  - data: {}
    service: light.turn_on
    target:
      entity_id: light.living_room
  alias: Turn on lights at sunset
  condition: []
  description: Turns on the living room lights when the sun sets
  id: '1741126746892'
  mode: single
  trigger:
  - event: sunset
    offset: +00:00:00
    platform: sun